"""Create User and Movie tables

Revision ID: 40390c2f5080
Revises:
Create Date: 2020-04-09 23:15:04.225817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40390c2f5080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('rated', sa.String(length=7), nullable=True),
    sa.Column('released', sa.String(length=15), nullable=True),
    sa.Column('runtime', sa.String(length=10), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('director', sa.String(length=50), nullable=True),
    sa.Column('writer', sa.String(length=200), nullable=True),
    sa.Column('actors', sa.String(length=200), nullable=True),
    sa.Column('plot', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('awards', sa.String(length=200), nullable=True),
    sa.Column('poster', sa.String(length=200), nullable=True),
    sa.Column('ratings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('metascore', sa.String(length=50), nullable=True),
    sa.Column('imdbrating', sa.String(length=50), nullable=True),
    sa.Column('imdbvotes', sa.String(length=50), nullable=True),
    sa.Column('imdbid', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('dvd', sa.String(length=50), nullable=True),
    sa.Column('boxoffice', sa.String(length=50), nullable=True),
    sa.Column('production', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('movies')
    # ### end Alembic commands ###
